"""Property-based tests for Plain Language Translator.

**Property 4: Plain Language Output**
**Validates: Requirements 2.5, 2.8, 6.1, 6.3, 6.4, 6.5, 9.1**

Tests that:
- Output SHALL NOT contain technical jargon from the blocklist
- Size values SHALL be translated to human-friendly descriptions
- Timestamps SHALL be translated to relative time descriptions
- Error messages SHALL contain both a problem description AND a suggested solution
"""

from datetime import datetime, timedelta
from typing import Any, Dict

import pytest
from hypothesis import given, settings, assume, HealthCheck
from hypothesis import strategies as st

from devbackup.language import (
    PlainLanguageTranslator,
    TECHNICAL_BLOCKLIST,
)


# Strategy for generating random byte sizes
size_strategy = st.integers(min_value=0, max_value=10 * 1024 * 1024 * 1024 * 1024)  # Up to 10TB

# Strategy for generating random file counts
file_count_strategy = st.integers(min_value=0, max_value=1_000_000)

# Strategy for generating random timestamps (within last year)
timestamp_strategy = st.datetimes(
    min_value=datetime.now() - timedelta(days=365),
    max_value=datetime.now() + timedelta(days=30),
)

# Strategy for generating random durations in seconds
duration_strategy = st.floats(min_value=0.0, max_value=86400.0)  # Up to 24 hours

# Strategy for generating status dictionaries
status_strategy = st.fixed_dictionaries({
    "status": st.sampled_from(["protected", "backing_up", "warning", "error", "unknown"]),
    "total_size": st.integers(min_value=0, max_value=10 * 1024 * 1024 * 1024 * 1024),
    "files_transferred": st.integers(min_value=0, max_value=1_000_000),
    "total_snapshots": st.integers(min_value=0, max_value=1000),
})


class TestPlainLanguageOutputProperty:
    """
    Property 4: Plain Language Output
    
    *For any* status response, error message, or notification generated by the system:
    - The output SHALL NOT contain technical jargon from the blocklist
    - Size values SHALL be translated to human-friendly descriptions
    - Timestamps SHALL be translated to relative time descriptions
    - Error messages SHALL contain both a problem description AND a suggested solution
    
    **Validates: Requirements 2.5, 2.8, 6.1, 6.3, 6.4, 6.5, 9.1**
    """
    
    @given(size_bytes=size_strategy)
    @settings(
        max_examples=100,
        deadline=None,
        suppress_health_check=[HealthCheck.too_slow],
    )
    def test_size_translation_no_technical_jargon(self, size_bytes: int):
        """
        Feature: user-experience-enhancement, Property 4: Plain Language Output
        
        Size translations SHALL NOT contain technical jargon from blocklist.
        
        **Validates: Requirements 6.4**
        """
        translator = PlainLanguageTranslator()
        
        # Test both translation methods
        result = translator.translate_size(size_bytes)
        result_precise = translator.translate_size_precise(size_bytes)
        
        # Verify no blocklisted terms appear
        assert not translator.contains_technical_jargon(result), \
            f"translate_size output '{result}' contains technical jargon"
        assert not translator.contains_technical_jargon(result_precise), \
            f"translate_size_precise output '{result_precise}' contains technical jargon"
    
    @given(size_bytes=size_strategy)
    @settings(
        max_examples=100,
        deadline=None,
        suppress_health_check=[HealthCheck.too_slow],
    )
    def test_size_translation_is_human_friendly(self, size_bytes: int):
        """
        Feature: user-experience-enhancement, Property 4: Plain Language Output
        
        Size translations SHALL be human-friendly descriptions.
        
        **Validates: Requirements 6.4**
        """
        translator = PlainLanguageTranslator()
        
        result = translator.translate_size(size_bytes)
        
        # Result should be non-empty
        assert result, "Size translation should not be empty"
        
        # Result should not contain raw byte values
        assert "bytes" not in result.lower(), \
            f"Size translation '{result}' should not contain 'bytes'"
        
        # Result should be readable text (contains letters)
        assert any(c.isalpha() for c in result), \
            f"Size translation '{result}' should contain readable text"
    
    @given(timestamp=timestamp_strategy)
    @settings(
        max_examples=100,
        deadline=None,
        suppress_health_check=[HealthCheck.too_slow],
    )
    def test_time_translation_no_technical_jargon(self, timestamp: datetime):
        """
        Feature: user-experience-enhancement, Property 4: Plain Language Output
        
        Time translations SHALL NOT contain technical jargon from blocklist.
        
        **Validates: Requirements 6.5**
        """
        translator = PlainLanguageTranslator()
        
        result = translator.translate_time(timestamp)
        
        # Verify no blocklisted terms appear
        assert not translator.contains_technical_jargon(result), \
            f"translate_time output '{result}' contains technical jargon"
    
    @given(timestamp=timestamp_strategy)
    @settings(
        max_examples=100,
        deadline=None,
        suppress_health_check=[HealthCheck.too_slow],
    )
    def test_time_translation_is_relative(self, timestamp: datetime):
        """
        Feature: user-experience-enhancement, Property 4: Plain Language Output
        
        Time translations SHALL be relative time descriptions.
        
        **Validates: Requirements 6.5**
        """
        translator = PlainLanguageTranslator()
        
        result = translator.translate_time(timestamp)
        
        # Result should be non-empty
        assert result, "Time translation should not be empty"
        
        # Result should not contain ISO 8601 format patterns
        assert "T" not in result or ":" not in result.split("T")[-1] if "T" in result else True, \
            f"Time translation '{result}' should not contain ISO 8601 format"
        
        # Result should not contain raw timestamps
        assert not any(c.isdigit() and len(result) > 10 and result.count("-") >= 2 for c in result), \
            f"Time translation '{result}' should not contain raw timestamps"
    
    @given(count=file_count_strategy)
    @settings(
        max_examples=100,
        deadline=None,
        suppress_health_check=[HealthCheck.too_slow],
    )
    def test_file_count_translation_no_technical_jargon(self, count: int):
        """
        Feature: user-experience-enhancement, Property 4: Plain Language Output
        
        File count translations SHALL NOT contain technical jargon from blocklist.
        
        **Validates: Requirements 6.4**
        """
        translator = PlainLanguageTranslator()
        
        result = translator.translate_file_count(count)
        
        # Verify no blocklisted terms appear
        assert not translator.contains_technical_jargon(result), \
            f"translate_file_count output '{result}' contains technical jargon"
    
    @given(
        status=st.sampled_from(["protected", "backing_up", "warning", "error"]),
        total_size=st.integers(min_value=0, max_value=10 * 1024 * 1024 * 1024 * 1024),
        files_transferred=st.integers(min_value=0, max_value=1_000_000),
        total_snapshots=st.integers(min_value=0, max_value=1000),
    )
    @settings(
        max_examples=100,
        deadline=None,
        suppress_health_check=[HealthCheck.too_slow],
    )
    def test_status_translation_no_technical_jargon(
        self,
        status: str,
        total_size: int,
        files_transferred: int,
        total_snapshots: int,
    ):
        """
        Feature: user-experience-enhancement, Property 4: Plain Language Output
        
        Status translations SHALL NOT contain technical jargon from blocklist.
        
        **Validates: Requirements 2.5, 2.8**
        """
        translator = PlainLanguageTranslator()
        
        status_dict = {
            "status": status,
            "total_size": total_size,
            "files_transferred": files_transferred,
            "total_snapshots": total_snapshots,
        }
        
        result = translator.translate_status(status_dict)
        
        # Verify no blocklisted terms appear
        assert not translator.contains_technical_jargon(result), \
            f"translate_status output '{result}' contains technical jargon"
    
    @given(
        error_type=st.sampled_from([
            "DestinationError",
            "SpaceError",
            "LockError",
            "ConfigurationError",
            "DiscoveryError",
            "RestoreError",
            "PermissionError",
            "FileNotFoundError",
            "OSError",
        ]),
    )
    @settings(
        max_examples=100,
        deadline=None,
        suppress_health_check=[HealthCheck.too_slow],
    )
    def test_error_translation_contains_problem_and_solution(self, error_type: str):
        """
        Feature: user-experience-enhancement, Property 4: Plain Language Output
        
        Error messages SHALL contain both a problem description AND a suggested solution.
        
        **Validates: Requirements 9.1**
        """
        translator = PlainLanguageTranslator()
        
        # Create an exception of the given type
        error_class = globals().get(error_type) or type(error_type, (Exception,), {})
        error = error_class("test error message")
        
        result = translator.translate_error(error)
        
        # Result should be non-empty
        assert result, "Error translation should not be empty"
        
        # Result should contain at least two sentences (problem + solution)
        # A sentence typically ends with . ! or ?
        sentences = [s.strip() for s in result.replace("!", ".").replace("?", ".").split(".") if s.strip()]
        assert len(sentences) >= 2, \
            f"Error translation '{result}' should contain problem AND solution (at least 2 sentences)"
    
    @given(
        error_type=st.sampled_from([
            "DestinationError",
            "SpaceError",
            "LockError",
            "ConfigurationError",
            "DiscoveryError",
            "RestoreError",
            "PermissionError",
            "FileNotFoundError",
            "OSError",
        ]),
    )
    @settings(
        max_examples=100,
        deadline=None,
        suppress_health_check=[HealthCheck.too_slow],
    )
    def test_error_translation_no_technical_jargon(self, error_type: str):
        """
        Feature: user-experience-enhancement, Property 4: Plain Language Output
        
        Error translations SHALL NOT contain technical jargon from blocklist.
        
        **Validates: Requirements 9.1**
        """
        translator = PlainLanguageTranslator()
        
        # Create an exception of the given type
        error_class = globals().get(error_type) or type(error_type, (Exception,), {})
        error = error_class("test error message")
        
        result = translator.translate_error(error)
        
        # Verify no blocklisted terms appear
        assert not translator.contains_technical_jargon(result), \
            f"translate_error output '{result}' contains technical jargon"
    
    @given(duration=duration_strategy)
    @settings(
        max_examples=100,
        deadline=None,
        suppress_health_check=[HealthCheck.too_slow],
    )
    def test_success_message_no_technical_jargon(self, duration: float):
        """
        Feature: user-experience-enhancement, Property 4: Plain Language Output
        
        Success messages SHALL NOT contain technical jargon from blocklist.
        
        **Validates: Requirements 6.1**
        """
        translator = PlainLanguageTranslator()
        
        # Use a generic snapshot name (should not appear in output)
        result = translator.success_backup("snapshot_2025-01-04-143022", duration)
        
        # Verify no blocklisted terms appear
        assert not translator.contains_technical_jargon(result), \
            f"success_backup output '{result}' contains technical jargon"
        
        # Verify snapshot name is not exposed to user
        assert "snapshot_2025" not in result, \
            f"success_backup output '{result}' should not expose snapshot name"


class TestBlocklistCompleteness:
    """
    Tests for blocklist completeness and sanitization.
    
    **Validates: Requirements 6.1, 6.4, 6.5**
    """
    
    @given(term=st.sampled_from(TECHNICAL_BLOCKLIST))
    @settings(
        max_examples=100,
        deadline=None,
        suppress_health_check=[HealthCheck.too_slow],
    )
    def test_blocklist_terms_detected(self, term: str):
        """
        Feature: user-experience-enhancement, Property 4: Plain Language Output
        
        All blocklisted terms SHALL be detected by contains_technical_jargon.
        
        **Validates: Requirements 6.1**
        """
        translator = PlainLanguageTranslator()
        
        # Create text containing the term
        test_text = f"This is a test with {term} in it"
        
        # Verify term is detected
        assert translator.contains_technical_jargon(test_text), \
            f"Blocklisted term '{term}' should be detected"
    
    @given(term=st.sampled_from(TECHNICAL_BLOCKLIST))
    @settings(
        max_examples=100,
        deadline=None,
        suppress_health_check=[HealthCheck.too_slow],
    )
    def test_sanitize_removes_blocklist_terms(self, term: str):
        """
        Feature: user-experience-enhancement, Property 4: Plain Language Output
        
        sanitize_output SHALL remove or replace blocklisted terms.
        
        **Validates: Requirements 6.1**
        """
        translator = PlainLanguageTranslator()
        
        # Create text containing the term
        test_text = f"This is a test with {term} in it"
        
        # Sanitize the text
        result = translator.sanitize_output(test_text)
        
        # Verify term is removed or replaced
        assert not translator.contains_technical_jargon(result), \
            f"Sanitized output '{result}' should not contain blocklisted term '{term}'"


class TestEdgeCases:
    """
    Edge case tests for the translator.
    
    **Validates: Requirements 6.1, 6.4, 6.5**
    """
    
    def test_negative_size_handled(self):
        """
        Feature: user-experience-enhancement, Property 4: Plain Language Output
        
        Negative sizes SHALL be handled gracefully.
        
        **Validates: Requirements 6.4**
        """
        translator = PlainLanguageTranslator()
        
        result = translator.translate_size(-100)
        
        # Should return a valid result, not crash
        assert result, "Should handle negative size"
        assert not translator.contains_technical_jargon(result)
    
    def test_negative_file_count_handled(self):
        """
        Feature: user-experience-enhancement, Property 4: Plain Language Output
        
        Negative file counts SHALL be handled gracefully.
        
        **Validates: Requirements 6.4**
        """
        translator = PlainLanguageTranslator()
        
        result = translator.translate_file_count(-100)
        
        # Should return a valid result, not crash
        assert result, "Should handle negative file count"
        assert not translator.contains_technical_jargon(result)
    
    def test_future_timestamp_handled(self):
        """
        Feature: user-experience-enhancement, Property 4: Plain Language Output
        
        Future timestamps SHALL be handled gracefully.
        
        **Validates: Requirements 6.5**
        """
        translator = PlainLanguageTranslator()
        
        future_time = datetime.now() + timedelta(hours=5)
        result = translator.translate_time(future_time)
        
        # Should return a valid result, not crash
        assert result, "Should handle future timestamp"
        assert not translator.contains_technical_jargon(result)
        # Should indicate future time
        assert "in" in result.lower() or "tomorrow" in result.lower() or "moment" in result.lower(), \
            f"Future time translation '{result}' should indicate future"
    
    def test_empty_status_dict_handled(self):
        """
        Feature: user-experience-enhancement, Property 4: Plain Language Output
        
        Empty status dictionaries SHALL be handled gracefully.
        
        **Validates: Requirements 2.5**
        """
        translator = PlainLanguageTranslator()
        
        result = translator.translate_status({})
        
        # Should return a valid result, not crash
        assert result, "Should handle empty status dict"
        assert not translator.contains_technical_jargon(result)
    
    def test_unknown_error_type_handled(self):
        """
        Feature: user-experience-enhancement, Property 4: Plain Language Output
        
        Unknown error types SHALL be handled gracefully.
        
        **Validates: Requirements 9.1**
        """
        translator = PlainLanguageTranslator()
        
        # Create a custom exception type
        class CustomUnknownError(Exception):
            pass
        
        error = CustomUnknownError("something went wrong")
        result = translator.translate_error(error)
        
        # Should return a valid result, not crash
        assert result, "Should handle unknown error type"
        assert not translator.contains_technical_jargon(result)
        # Should still have problem + solution structure
        sentences = [s.strip() for s in result.replace("!", ".").replace("?", ".").split(".") if s.strip()]
        assert len(sentences) >= 2, \
            f"Unknown error translation '{result}' should still have problem AND solution"
